# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tim MacDonald
sub_title: PHP, Laravel, and Mobile App Developer
site_description: I'm a local software developer located in Wagga Wagga, Australia specialising in PHP / Laravel web apps, but also takle Android and iOS apps when possible.
description: Software developer, musician and native plant enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://timacdonald.me" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title/
twitter_url: https://twitter.com/timacdonald87
github_url: https://github.com/timacdonald
linkedin_url: https://au.linkedin.com/in/timacdonaldau
asset_version: 290327

# Build settings
destination: ../public_html
markdown: kramdown
include:
  - .error-pages
  - .htaccess
exclude:
  - Gemfile
  - Gemfile.lock
  - webpack.mix.js
  - webpack.config.js
  - package.json
  - mix-manifest.json
  - node_modules